### ISSUE TITLE
Missing Argument queries in version 0.2.11

### ISSUE THREAD

**Issue by LuRe97** [milvus-io/milvus-model#56]
Hello, we are using FlagEmbedding 1.3.3 and milvus-model 0.2.11 and suddenly get the following error:
"M3Embedder.encode() missing 1 required positional argument: 'queries'"
on this line:
output = self.model.encode(sentences=texts, **self._encode_config)

Timing wise it could very well be related with the changes in the 0.2.11 version because of this issue: https://github.com/milvus-io/milvus-model/issues/52

Downgrading to version 0.2.10 fixes the issue for now.

**Comment by wxywb** [comment]
I tested it in a Colab enironment and it shows milvus-model 0.2.11 works well with FlagEmbedding 1.3.3
https://colab.research.google.com/drive/1SrTd-En5-NdoWNvICxBkJ-SfBniyyd0j#scrollTo=xD6uQ6C9qI7R

And `sentences`(instead of `queries`) is the argument of `encode` function in latest version of FlagEmbedding. https://github.com/FlagOpen/FlagEmbedding/blob/aeafc7e4d4a9905a3d8468934f370686077694ec/FlagEmbedding/inference/embedder/encoder_only/m3.py#L263-L271
